import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={` relative ${inter.className} flex`}>
        <div className="z-10 absolute h-[8vh] bg-black">
          <NavBar />
        </div>
        <div className="pt-[8vh] min-w-[100vw] min-h-screen bg-black">{children}</div>
      </body>
    </html>
  );
}
