import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-black relative ${inter.className}`}>
        <div className="z-10 absolute">
          <NavBar />
        </div>
        {children}
      </body>
    </html>
  );
}
